{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 dim;\nuniform float iTime;\nuniform vec3 bmh;\n\nvec4 fragColor;\n\nvec3 flutterNavy;\nvec3 flutterBlue;\nvec4 flutterSky;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    flutterNavy = vec3(0.01568627543747425079345703125, 0.16862745583057403564453125, 0.3490196168422698974609375);\n    flutterBlue = vec3(0.01960784383118152618408203125, 0.3254902064800262451171875, 0.69411766529083251953125);\n    flutterSky = vec4(0.007843137718737125396728515625, 0.4901960790157318115234375, 0.99215686321258544921875, 1.0);\n    vec2 p = FLT_flutter_local_FlutterFragCoord() / dim;\n    vec2 q = p - vec2(0.5);\n    vec4 col = vec4(bmh * p.xyx, bmh.z);\n    float r = bmh.z + ((1.0 * sin(iTime)) * cos(atan(q.x, q.y) * (((3.0 * bmh.y) + (3.0 * bmh.x)) + (3.0 * bmh.z))));\n    col *= (r * length(q));\n    fragColor = col;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 0,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "dim",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "iTime",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "bmh",
      "rows": 3,
      "type": 10
    }
  ]
}