{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform float iTime;\nuniform vec3 sound;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_random(vec2 st)\n{\n    return fract(sin(dot(st, vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nfloat FLT_flutter_local_noise(vec2 st)\n{\n    vec2 i = floor(st);\n    vec2 f = fract(st);\n    vec2 param = i;\n    float a = FLT_flutter_local_random(param);\n    vec2 param_1 = i + vec2(1.0, 0.0);\n    float b = FLT_flutter_local_random(param_1);\n    vec2 param_2 = i + vec2(0.0, 1.0);\n    float c = FLT_flutter_local_random(param_2);\n    vec2 param_3 = i + vec2(1.0);\n    float d = FLT_flutter_local_random(param_3);\n    vec2 u = (f * f) * (vec2(3.0) - (f * 2.0));\n    return (mix(a, b, u.x) + (((c - a) * u.y) * (1.0 - u.x))) + (((d - b) * u.x) * u.y);\n}\n\nvoid FLT_main()\n{\n    vec2 st_1 = flutter_FragCoord.xy / u_resolution;\n    vec2 pos = vec2(st_1 * 5.0);\n    vec2 param_4 = pos * sound.xz;\n    float n = FLT_flutter_local_noise(param_4);\n    pos = vec2(0.5) - st_1;\n    float r = (((length(pos) * 3.0) * 2.0) * sin(iTime)) * (1.0 / sound.x);\n    float a_1 = atan(pos.y, pos.x);\n    float f_1 = cos((3.0 * ((sound.x + sound.y) + sound.z)) * a_1);\n    float q = smoothstep(cos(f_1 + iTime), cos(f_1) + n, r);\n    vec2 param_5 = pos * iTime;\n    fragColor = vec4(((sound * q) * st_1.xyx) * FLT_flutter_local_noise(param_5), 0.001000000047497451305389404296875);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 0,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "u_resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "iTime",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "sound",
      "rows": 3,
      "type": 10
    }
  ]
}