{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform vec3 camera;\nuniform vec3 target;\nuniform vec3 sound;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_random(vec2 uv)\n{\n    return fract(sin(dot(uv, vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nfloat FLT_flutter_local_noise(vec2 uv)\n{\n    vec2 i = floor(uv);\n    vec2 f = fract(uv);\n    f = (f * f) * (vec2(3.0) - (f * 2.0));\n    vec2 param = i + vec2(0.0);\n    float lb = FLT_flutter_local_random(param);\n    vec2 param_1 = i + vec2(1.0, 0.0);\n    float rb = FLT_flutter_local_random(param_1);\n    vec2 param_2 = i + vec2(0.0, 1.0);\n    float lt = FLT_flutter_local_random(param_2);\n    vec2 param_3 = i + vec2(1.0);\n    float rt = FLT_flutter_local_random(param_3);\n    return mix(mix(lb, rb, f.x), mix(lt, rt, f.x), f.y);\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = (FLT_flutter_local_FlutterFragCoord() - (iResolution * 0.5)) / vec2(iResolution.y);\n    vec2 param_4 = vec2(iTime);\n    float n = FLT_flutter_local_noise(param_4);\n    float l = length(uv_1);\n    fragColor = vec4(((0.5 * sound.z) * (sound.x + sound.y)) + (n * n), n * 0.100000001490116119384765625, l * l, 1.0) * 0.4000000059604644775390625;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 0,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "iResolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "iTime",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "camera",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 3,
      "name": "target",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 4,
      "name": "sound",
      "rows": 3,
      "type": 10
    }
  ]
}